package embwasm:demo;
 
/// @cpp-header: "host_apis.hpp"
world hello {
    /// @cpp-func: embwasm::Print
    import print: func(val: s32);

    /// @cpp-func: embwasm::PrintChar
    import print-char: func(character: s32);

    /// @cpp-func: embwasm::PrintVal
    import print-val: func(val: s32);
}
