package embwasm:demo;
 
/// @cpp-header: "host_apis.hpp"
world hello {
    /// @cpp-func: embwasm::Print
    import print: func(val: i32);

    /// @cpp-func: embwasm::PrintChar
    import print-char: func(character: i32);

    /// @cpp-func: embwasm::PrintVal
    import print-val: func(val: i32);
}
