# WASM Host Module Configuration for Demo
# Maps WASM imports to C++ host functions.

# 静的検索コードにインクルードするヘッダーファイル一覧
headers:
  - "host_apis.hpp"

# モジュール名をキーにした API のマッピング一覧
# ( module と field の辞書順で自動ソートされます )
modules:
  env:
    apis:
      - field: print
        function: embwasm::Print

      - field: print_char
        function: embwasm::PrintChar

      - field: print_val
        function: embwasm::PrintVal
