package embwasm:test;

/// @wit-import: "../../wasm_host_modules/wit/sys_rt/stdio.wit"
/// @cpp-init: embwasm::TestEnvInit
/// @cpp-deinit: embwasm::TestEnvDeinit
/// @cpp-header: "host_apis.hpp"
world test-env {
    import dummy: func();

    import print-char: func(character: s32);

    import print-val: func(val: s32);
}
