package sys:rt;

/// @cpp-header: "embwasm_hostmodule_thread.hpp"
interface threads {
    thread-spawn: func(name: string) -> s32;

    thread-yield: func();

    event-wait: func(event-id: s32);

    event-signal: func(event-id: s32);
}
