#!/usr/bin/env python3
import os
import sys

def main():
    # 引数の処理
    config_path = sys.argv[1] if len(sys.argv) > 1 else 'api_config.yaml'
    out_cpp_path = sys.argv[2] if len(sys.argv) > 2 else 'src/wasm_api_static.cpp'
    out_h_path = sys.argv[3] if len(sys.argv) > 3 else 'include/wasm_api_static.h'

    if not os.path.exists(config_path):
        print(f"Error: Configuration file '{config_path}' not found.", file=sys.stderr)
        sys.exit(1)

    apis = []
    headers = []

    # YAMLのロード（PyYAMLがなければ標準機能ベースの簡易フォールバックパーサーを使用）
    try:
        import yaml
        with open(config_path, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)
            apis = data.get('apis', [])
            headers = data.get('headers', [])
    except ImportError:
        current_section = None
        current_api = {}
        with open(config_path, 'r', encoding='utf-8') as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith('#'):
                    continue
                # セクション切り替えの検知
                if stripped.startswith('headers:'):
                    current_section = 'headers'
                    continue
                elif stripped.startswith('apis:'):
                    current_section = 'apis'
                    continue

                if current_section == 'headers':
                    if stripped.startswith('-'):
                        header_val = stripped.lstrip('-').strip().strip("'").strip('"')
                        headers.append(header_val)
                elif current_section == 'apis':
                    if stripped.startswith('-'):
                        if current_api:
                            apis.append(current_api)
                            current_api = {}
                        stripped = stripped.lstrip('-').strip()
                    if ':' in stripped:
                        key, val = stripped.split(':', 1)
                        val_str = val.strip().strip("'").strip('"')
                        current_api[key.strip()] = val_str
            if current_api:
                apis.append(current_api)

    # 二分探索をするため、(module, field) の辞書順でソート
    apis.sort(key=lambda x: (x['module'], x['field']))

    # ヘッダーファイルの内容生成
    h_content = """// =============================================================================
// Copyright (c) 2026 embwasm Project. All rights reserved.
// [Auto-generated by gen_api.py] - DO NOT EDIT DIRECTLY
// =============================================================================

#ifndef EMBWASM_WASM_API_STATIC_H_
#define EMBWASM_WASM_API_STATIC_H_

#include "wasm_types.h"

namespace embwasm {

// 静的に登録されたホストAPIを二分探索で高速検索します。
// O(log N) の計算量で検索が完了します。
HostFunction LookupStaticHostFunction(const char* module_name, const char* field_name) noexcept;

} // namespace embwasm

#endif // EMBWASM_WASM_API_STATIC_H_
"""

    # インクルード指示子の生成
    include_directives = []
    for h in headers:
        include_directives.append(f'#include "{h}"')
    include_directives_str = "\n".join(include_directives)

    # ソースファイルのエントリ生成
    cpp_entries = []
    for api in apis:
        cpp_entries.append(f'    {{ "{api["module"]}", "{api["field"]}", {api["function"]} }}')
    
    cpp_entries_str = ",\n".join(cpp_entries)

    # ソースファイルの内容生成
    cpp_content = f"""// =============================================================================
// Copyright (c) 2026 embwasm Project. All rights reserved.
// [Auto-generated by gen_api.py] - DO NOT EDIT DIRECTLY
// =============================================================================

#include "wasm_api_static.h"
{include_directives_str}
#include <cstring>

namespace embwasm {{

struct StaticApiEntry {{
    const char* module_name;
    const char* field_name;
    HostFunction function;
}};

// アルファベット順にソートされた静的テーブル (二分探索用)
static const StaticApiEntry kStaticApiTable[] = {{
{cpp_entries_str}
}};
static constexpr std::size_t kStaticApiTableSize = sizeof(kStaticApiTable) / sizeof(kStaticApiTable[0]);

HostFunction LookupStaticHostFunction(const char* module_name, const char* field_name) noexcept {{
    int low = 0;
    int high = static_cast<int>(kStaticApiTableSize) - 1;

    while (low <= high) {{
        int mid = low + (high - low) / 2;
        const auto& entry = kStaticApiTable[mid];

        int mod_cmp = std::strcmp(module_name, entry.module_name);
        if (mod_cmp == 0) {{
            int field_cmp = std::strcmp(field_name, entry.field_name);
            if (field_cmp == 0) {{
                return entry.function;
            }} else if (field_cmp < 0) {{
                high = mid - 1;
            }} else {{
                low = mid + 1;
            }}
        }} else if (mod_cmp < 0) {{
            high = mid - 1;
        }} else {{
            low = mid + 1;
        }}
    }}

    return nullptr;
}}

}} // namespace embwasm
"""

    # フォルダの作成
    os.makedirs(os.path.dirname(os.path.abspath(out_cpp_path)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.abspath(out_h_path)), exist_ok=True)

    # 書き込み
    with open(out_h_path, 'w', encoding='utf-8') as f:
        f.write(h_content)
    with open(out_cpp_path, 'w', encoding='utf-8') as f:
        f.write(cpp_content)

    print(f"Generated {out_h_path} and {out_cpp_path} from {config_path}")

if __name__ == '__main__':
    main()
