// =============================================================================
// Copyright (c) 2026 embwasm Project. All rights reserved.
// [Auto-generated by gen_api.py / manually adjusted return types]
// =============================================================================

#ifndef EMBWASM_GENERATED_WASM_API_H_
#define EMBWASM_GENERATED_WASM_API_H_

#ifdef __cplusplus
extern "C" {
#endif

// ---------------------------------------------------------------------------
// wasi:sockets - ソケット操作インポート宣言
// WASM モジュール側でこのヘッダーをインクルードすることで
// import_module / import_name 属性付きの宣言が使用できる。
// ---------------------------------------------------------------------------

__attribute__((import_module("wasi_sockets"), import_name("socket_create")))
int socket_create(int domain, int type, int protocol);

__attribute__((import_module("wasi_sockets"), import_name("socket_close")))
int socket_close(int sock);

__attribute__((import_module("wasi_sockets"), import_name("socket_bind")))
int socket_bind(int sock, int addr_ptr, int addr_len);

__attribute__((import_module("wasi_sockets"), import_name("socket_listen")))
int socket_listen(int sock, int backlog);

__attribute__((import_module("wasi_sockets"), import_name("socket_accept")))
int socket_accept(int sock, int peer_addr_ptr, int peer_addr_len_ptr);

__attribute__((import_module("wasi_sockets"), import_name("socket_connect")))
int socket_connect(int sock, int addr_ptr, int addr_len);

__attribute__((import_module("wasi_sockets"), import_name("socket_send")))
int socket_send(int sock, int buf_ptr, int buf_len, int flags);

__attribute__((import_module("wasi_sockets"), import_name("socket_recv")))
int socket_recv(int sock, int buf_ptr, int buf_len, int flags);

__attribute__((import_module("wasi_sockets"), import_name("socket_send_to")))
int socket_send_to(int sock, int buf_ptr, int buf_len, int flags, int addr_ptr, int addr_len);

__attribute__((import_module("wasi_sockets"), import_name("socket_recv_from")))
int socket_recv_from(int sock, int buf_ptr, int buf_len, int flags, int src_addr_ptr, int src_addr_len_ptr);

__attribute__((import_module("wasi_sockets"), import_name("socket_set_opt")))
int socket_set_opt(int sock, int level, int optname, int optval_ptr, int optlen);

__attribute__((import_module("wasi_sockets"), import_name("socket_get_opt")))
int socket_get_opt(int sock, int level, int optname, int optval_ptr, int optlen_ptr);

__attribute__((import_module("wasi_sockets"), import_name("socket_set_non_blocking")))
int socket_set_non_blocking(int sock, int nonblocking);

__attribute__((import_module("wasi_sockets"), import_name("socket_poll")))
int socket_poll(int sock, int events, int timeout_ms);

__attribute__((import_module("wasi_sockets"), import_name("inet_addr")))
int inet_addr(int addr_str_ptr);

__attribute__((import_module("wasi_sockets"), import_name("host_to_net_short")))
int host_to_net_short(int host_short);

__attribute__((import_module("wasi_sockets"), import_name("net_to_host_short")))
int net_to_host_short(int net_short);

__attribute__((import_module("wasi_sockets"), import_name("socket_get_last_error")))
int socket_get_last_error(void);

#ifdef __cplusplus
}
#endif

#endif  // EMBWASM_GENERATED_WASM_API_H_
