# WASM Host API Configuration for Demo
# Maps WASM imports to C++ host functions.

# 静的検索コードにインクルードするヘッダーファイル一覧
headers:
  - "host_apis.h"

# API のマッピング一覧 ( module と field の辞書順で自動ソートされます )
apis:
  - module: env
    field: print
    function: embwasm::Print

  - module: env
    field: print_char
    function: embwasm::PrintChar

  - module: env
    field: print_val
    function: embwasm::PrintVal
