#!/usr/bin/env python3
"""Analyze static stack usage from .su files generated by clang/gcc -fstack-usage.

Without a call graph: sums all static frames (gross over-estimate, original behavior).
With a call graph, finds the maximum-weight call path in the DAG for an accurate
worst-case stack depth.

Call graph sources (in priority order when multiple are given)
--------------------------------------------------------------
opt:   --compile-commands compile_commands.json [--opt /path/to/opt]
       Recompiles each TU with -emit-llvm, runs opt -passes=print-callgraph.
       Works with any Clang build. Requires cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON.
GCC:   add -fcallgraph-info=su to compile flags → .ci files appear next to .su files.
       Pass --dir <build-dir> and .ci files are picked up automatically.
JSON:  --callgraph file.json
       { "caller_mangled_sym": ["callee_mangled_sym", ...], ... }
"""

import sys
import os
import math
import glob
import argparse
import json
import subprocess
import shlex
import hashlib
import tempfile
import shutil
import re
from collections import defaultdict, deque


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def parse_su_file(path):
    entries = []
    if not os.path.exists(path):
        print(f"  Warning: {path} not found, skipping", file=sys.stderr)
        return entries
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Format: /path/file.c:line:col:function_name\tsize\tqualifier
            parts = line.split('\t')
            if len(parts) < 3:
                continue
            func_name = parts[0].rsplit(':', 1)[-1]
            size = int(parts[1])
            qualifier = parts[2].strip()
            entries.append((func_name, size, qualifier))
    return entries


def parse_ci_file(path):
    """Parse GCC -fcallgraph-info .ci files.
    Format per line: /path/file.c:line:col:caller \\t /path/file.c:line:col:callee
    """
    edges = []
    if not os.path.exists(path):
        return edges
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) < 2:
                continue
            caller = parts[0].rsplit(':', 1)[-1]
            callee = parts[1].rsplit(':', 1)[-1]
            edges.append((caller, callee))
    return edges


def collect_su_files(directory):
    return glob.glob(os.path.join(directory, '**/*.su'), recursive=True)


def collect_ci_files(directory):
    return glob.glob(os.path.join(directory, '**/*.ci'), recursive=True)


# ---------------------------------------------------------------------------
# Call graph extraction via opt
# ---------------------------------------------------------------------------

def _transform_compile_command(args, bc_path):
    """Return a new arg list that emits LLVM bitcode to bc_path instead of an object file."""
    new_args = []
    i = 0
    has_c = False
    while i < len(args):
        arg = args[i]
        if arg == '-o' and i + 1 < len(args):
            new_args.extend(['-o', bc_path])
            i += 2
        elif arg.startswith('-o') and len(arg) > 2:
            new_args.append(f'-o{bc_path}')
            i += 1
        elif arg == '-Werror':
            i += 1  # drop: avoids failing on warnings during analysis recompile
        elif arg == '-c':
            has_c = True
            new_args.append(arg)
            i += 1
        else:
            new_args.append(arg)
            i += 1
    if not has_c:
        new_args.append('-c')
    if '-emit-llvm' not in new_args:
        new_args.append('-emit-llvm')
    return new_args


def _parse_opt_output(text):
    """Parse opt -passes=print-callgraph stderr output into (caller, callee) pairs."""
    edges = []
    current_func = None
    for line in text.split('\n'):
        m = re.match(r"Call graph node for function: '([^']+)'", line)
        if m:
            current_func = m.group(1)
            continue
        if current_func:
            m = re.match(r"\s+CS<[^>]+> calls function '([^']+)'", line)
            if m:
                edges.append((current_func, m.group(1)))
    return edges


def extract_callgraph_via_opt(compile_commands_path, opt_bin,
                              include_patterns=None, keep_tmp=False):
    """Recompile every TU with -emit-llvm, run opt, return (caller, callee) edge list.

    include_patterns: list of glob patterns (matched against source file path).
                      If empty/None, all entries are processed.
    """
    import fnmatch

    with open(compile_commands_path) as f:
        entries = json.load(f)

    if include_patterns:
        entries = [
            e for e in entries
            if any(fnmatch.fnmatch(e.get('file', ''), pat) for pat in include_patterns)
        ]

    tmpdir = tempfile.mkdtemp(prefix='embwasm_cg_')
    edges = []
    print(f"[opt] Extracting call graph from {len(entries)} translation unit(s)...",
          file=sys.stderr)

    for entry in entries:
        src_file = entry.get('file', '')
        cwd = entry.get('directory', os.getcwd())

        # Build arg list from 'command' string or 'arguments' array
        if 'arguments' in entry:
            raw_args = list(entry['arguments'])
        else:
            raw_args = shlex.split(entry.get('command', ''))

        if not raw_args:
            continue

        # Derive a unique .bc filename from the source path
        src_hash = hashlib.md5(src_file.encode()).hexdigest()[:8]
        bc_name = os.path.splitext(os.path.basename(src_file))[0] + f'_{src_hash}.bc'
        bc_path = os.path.join(tmpdir, bc_name)

        new_args = _transform_compile_command(raw_args, bc_path)

        result = subprocess.run(new_args, cwd=cwd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"  Warning: recompile failed for {os.path.basename(src_file)}: "
                  f"{result.stderr.strip()[:120]}", file=sys.stderr)
            continue

        if not os.path.exists(bc_path):
            print(f"  Warning: no .bc produced for {os.path.basename(src_file)}",
                  file=sys.stderr)
            continue

        opt_result = subprocess.run(
            [opt_bin, '-passes=print-callgraph', bc_path, '-o', '/dev/null'],
            capture_output=True, text=True
        )
        file_edges = _parse_opt_output(opt_result.stderr)
        edges.extend(file_edges)
        print(f"  {os.path.basename(src_file)}: {len(file_edges)} call edges", file=sys.stderr)

    if not keep_tmp:
        shutil.rmtree(tmpdir, ignore_errors=True)
    else:
        print(f"[opt] Bitcode files kept in: {tmpdir}", file=sys.stderr)

    print(f"[opt] Total: {len(edges)} call edges extracted.", file=sys.stderr)
    return edges


# ---------------------------------------------------------------------------
# Demangling
# ---------------------------------------------------------------------------

def demangle_names(names):
    """Return a dict {mangled: demangled} using c++filt."""
    if not names:
        return {}
    try:
        result = subprocess.run(
            ['c++filt'],
            input='\n'.join(names),
            capture_output=True, text=True, timeout=10
        )
        demangled = result.stdout.strip().split('\n')
        return dict(zip(names, demangled))
    except Exception:
        return {n: n for n in names}


# ---------------------------------------------------------------------------
# Call graph helpers
# ---------------------------------------------------------------------------

def build_call_graph(edges):
    """Build forward/reverse adjacency sets from edge list."""
    callees = defaultdict(set)
    callers = defaultdict(set)
    all_nodes = set()
    for caller, callee in edges:
        callees[caller].add(callee)
        callers[callee].add(caller)
        all_nodes.add(caller)
        all_nodes.add(callee)
    return callees, callers, all_nodes


def topological_sort(nodes, callees):
    """Kahn's algorithm. Returns ordered list, or None if a cycle is detected."""
    in_degree = {n: 0 for n in nodes}
    for node in nodes:
        for callee in callees.get(node, set()):
            if callee in in_degree:
                in_degree[callee] += 1

    queue = deque(n for n, d in in_degree.items() if d == 0)
    order = []
    while queue:
        node = queue.popleft()
        order.append(node)
        for callee in callees.get(node, set()):
            if callee not in in_degree:
                continue
            in_degree[callee] -= 1
            if in_degree[callee] == 0:
                queue.append(callee)

    return order if len(order) == len(nodes) else None


# ---------------------------------------------------------------------------
# Analysis modes
# ---------------------------------------------------------------------------

def find_max_stack_path(frame_sizes, callees, callers, all_nodes):
    """DP over the call-graph DAG to find the worst-case cumulative stack depth.

    Returns (max_cost, path_list).
    """
    for name in frame_sizes:
        all_nodes.add(name)

    order = topological_sort(all_nodes, callees)
    if order is None:
        return None, []

    max_cost = {}
    predecessor = {}

    for node in order:
        frame = frame_sizes.get(node, 0)
        node_callers = [p for p in callers.get(node, set()) if p in max_cost]
        if not node_callers:
            max_cost[node] = frame
            predecessor[node] = None
        else:
            best_pred = max(node_callers, key=lambda p: max_cost[p])
            max_cost[node] = max_cost[best_pred] + frame
            predecessor[node] = best_pred

    if not max_cost:
        return 0, []

    leaves = [n for n in all_nodes if not callees.get(n)]
    if not leaves:
        leaves = list(all_nodes)

    worst_leaf = max(leaves, key=lambda n: max_cost.get(n, 0))
    worst_cost = max_cost[worst_leaf]

    path = []
    node = worst_leaf
    while node is not None:
        path.append(node)
        node = predecessor.get(node)
    path.reverse()

    return worst_cost, path


def next_power_of_2(n):
    if n <= 1:
        return 1
    return 1 << math.ceil(math.log2(n))


def analyze_with_callgraph(frame_sizes, dynamic_funcs, callees, callers,
                           all_nodes, label="", demangle=False):
    header = "=== WASM Static Stack Analysis (Call-Graph)"
    if label:
        header += f" [{label}]"
    header += " ==="
    print(header)

    max_stack, path = find_max_stack_path(frame_sizes, callees, callers, all_nodes)

    if max_stack is None:
        print("ERROR: Cycle detected in call graph — recursion prohibition violated!",
              file=sys.stderr)
        sys.exit(1)

    name_map = demangle_names(path) if demangle else {n: n for n in path}

    print(f"\nWorst-case call path  ({len(path)} frames, {max_stack} bytes):")
    cumulative = 0
    for func in path:
        frame = frame_sizes.get(func, 0)
        cumulative += frame
        indent = "  " * path.index(func)
        print(f"  {indent}{name_map.get(func, func)}  +{frame}  (cumulative: {cumulative})")

    print()
    if dynamic_funcs:
        print("Warning: dynamic stack usage (VLA/alloca) detected in:")
        for fn in dynamic_funcs:
            display = name_map.get(fn, fn) if demangle else fn
            print(f"  - {display}")
        print()

    recommended = next_power_of_2(max(max_stack, 64))
    print(f"Worst-case stack depth: {max_stack} bytes")
    print(f"Recommended stack-size: {recommended}  (next power of 2)")
    print(f"Linker flag           : -Wl,-z,stack-size={recommended}")


def analyze_simple(all_entries, label="", demangle=False):
    header = "=== WASM Static Stack Analysis (No Call-Graph)"
    if label:
        header += f" [{label}]"
    header += " ==="
    print(header)
    print("WARNING: No call graph provided. Summing ALL frames — result is a gross"
          " over-estimate.\n"
          "         Use GCC -fcallgraph-info=su or --callgraph JSON for accurate analysis.\n")

    static_total = 0
    dynamic_funcs = []
    all_names = [name for name, _, _ in all_entries]
    name_map = demangle_names(all_names) if demangle else {n: n for n in all_names}
    max_name_len = max((len(name_map[n]) for n, _, _ in all_entries), default=10)

    for func_name, size, qualifier in sorted(all_entries, key=lambda x: -x[1]):
        display = name_map.get(func_name, func_name)
        flag = " [!]" if "dynamic" in qualifier else ""
        print(f"  {display:{max_name_len}} : {size:5d} bytes [{qualifier}]{flag}")
        if qualifier == "static":
            static_total += size
        elif "dynamic" in qualifier:
            dynamic_funcs.append(func_name)

    print()
    if dynamic_funcs:
        print("Warning: dynamic stack usage (VLA/alloca) detected in:")
        for fn in dynamic_funcs:
            print(f"  - {name_map.get(fn, fn)}")
        print()

    recommended = next_power_of_2(max(static_total, 64))
    print(f"Sum of static frames  : {static_total} bytes  (conservative upper bound)")
    print(f"Recommended stack-size: {recommended}  (next power of 2)")
    print(f"Linker flag           : -Wl,-z,stack-size={recommended}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--dir", metavar="DIR",
                        help="Scan directory recursively for .su and .ci files")
    parser.add_argument("--label", metavar="LABEL", default="",
                        help="Label shown in analysis header")
    parser.add_argument("--callgraph", metavar="FILE",
                        help='JSON call graph: {"caller_sym": ["callee_sym", ...], ...}')
    parser.add_argument("--compile-commands", metavar="FILE",
                        help="compile_commands.json (cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON);"
                             " recompiles with -emit-llvm and runs opt to extract call graph")
    parser.add_argument("--opt", metavar="PATH", default="opt",
                        help="Path to the opt binary (default: opt from PATH)."
                             " Homebrew: /opt/homebrew/bin/opt")
    parser.add_argument("--cc-include", metavar="GLOB", action="append", default=[],
                        dest="cc_include",
                        help="Glob pattern to filter compile_commands entries by source file"
                             " path (can repeat). Example: --cc-include '*/src/*.cpp'")
    parser.add_argument("--keep-tmp", action="store_true",
                        help="Keep temporary .bc files (useful for debugging)")
    parser.add_argument("--demangle", action="store_true",
                        help="Demangle C++ symbol names in output (requires c++filt)")
    parser.add_argument("su_files", nargs="*", metavar="FILE",
                        help=".su files to analyze")
    args = parser.parse_args()

    su_paths = list(args.su_files)
    ci_paths = []

    if args.dir:
        su_paths.extend(collect_su_files(args.dir))
        ci_paths.extend(collect_ci_files(args.dir))

    if not su_paths and not args.compile_commands:
        parser.print_help()
        sys.exit(1)

    all_entries = []
    for path in su_paths:
        all_entries.extend(parse_su_file(path))

    if not all_entries:
        print("No stack usage data found.")
        return

    frame_sizes = {}
    dynamic_funcs = []
    for func_name, size, qualifier in all_entries:
        frame_sizes[func_name] = max(frame_sizes.get(func_name, 0), size)
        if "dynamic" in qualifier:
            dynamic_funcs.append(func_name)

    # Collect call graph edges (opt > .ci > JSON, all additive)
    edges = []

    if args.compile_commands:
        edges.extend(extract_callgraph_via_opt(
            args.compile_commands, args.opt,
            include_patterns=args.cc_include or None,
            keep_tmp=args.keep_tmp))

    for path in ci_paths:
        edges.extend(parse_ci_file(path))

    if args.callgraph:
        with open(args.callgraph) as f:
            cg = json.load(f)
        for caller, callees_list in cg.items():
            for callee in callees_list:
                edges.append((caller, callee))

    if edges:
        callees, callers, all_nodes = build_call_graph(edges)
        analyze_with_callgraph(frame_sizes, dynamic_funcs, callees, callers,
                               all_nodes, label=args.label, demangle=args.demangle)
    else:
        analyze_simple(all_entries, label=args.label, demangle=args.demangle)


if __name__ == "__main__":
    main()
