#!/usr/bin/env python3
"""Analyze static stack usage from .su files generated by clang/gcc -fstack-usage."""

import sys
import os
import math
import glob
import argparse


def parse_su_file(path):
    entries = []
    if not os.path.exists(path):
        print(f"  Warning: {path} not found, skipping", file=sys.stderr)
        return entries
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Format: /path/to/file.c:line:col:function_name\tsize\tqualifier
            parts = line.split('\t')
            if len(parts) < 3:
                continue
            func_name = parts[0].rsplit(':', 1)[-1]
            size = int(parts[1])
            qualifier = parts[2].strip()
            entries.append((func_name, size, qualifier))
    return entries


def collect_su_files(directory):
    return glob.glob(os.path.join(directory, '**/*.su'), recursive=True)


def next_power_of_2(n):
    if n <= 1:
        return 1
    return 1 << math.ceil(math.log2(n))


def analyze(su_paths, label=""):
    all_entries = []
    for path in su_paths:
        all_entries.extend(parse_su_file(path))

    if not all_entries:
        print("No stack usage data found.")
        return

    header = f"=== WASM Static Stack Analysis"
    if label:
        header += f" [{label}]"
    header += " ==="
    print(header)

    static_total = 0
    dynamic_funcs = []
    max_name_len = max(len(name) for name, _, _ in all_entries)

    for func_name, size, qualifier in sorted(all_entries, key=lambda x: -x[1]):
        flag = " [!]" if "dynamic" in qualifier else ""
        print(f"  {func_name:{max_name_len}} : {size:5d} bytes [{qualifier}]{flag}")
        if qualifier == "static":
            static_total += size
        elif "dynamic" in qualifier:
            dynamic_funcs.append(func_name)

    print()

    if dynamic_funcs:
        print("Warning: dynamic stack usage (VLA/alloca) detected in:")
        for fn in dynamic_funcs:
            print(f"  - {fn}")
        print()

    recommended = next_power_of_2(max(static_total, 64))
    print(f"Sum of static frames  : {static_total} bytes  (conservative upper bound)")
    print(f"Recommended stack-size: {recommended}  (next power of 2)")
    print(f"Linker flag           : -Wl,-z,stack-size={recommended}")


def main():
    parser = argparse.ArgumentParser(
        description="Analyze static stack usage from .su files."
    )
    parser.add_argument("--dir", metavar="DIR",
                        help="Scan directory recursively for .su files")
    parser.add_argument("--label", metavar="LABEL", default="",
                        help="Label shown in analysis header")
    parser.add_argument("su_files", nargs="*", metavar="FILE",
                        help=".su files to analyze")
    args = parser.parse_args()

    su_paths = list(args.su_files)
    if args.dir:
        su_paths.extend(collect_su_files(args.dir))

    if not su_paths:
        parser.print_help()
        sys.exit(1)

    analyze(su_paths, label=args.label)


if __name__ == "__main__":
    main()
