package embwasm:stdio;

/// @cpp-module: stdio
/// @cpp-header: "embwasm_hostmodule_stdio.hpp"
interface stdio {
    /// @cpp-func: embwasm::hostmodules::stdio::Printf
    printf: func(fmt: string, args: list<s32>);

    /// @cpp-func: embwasm::hostmodules::stdio::Puts
    puts: func(s: string) -> s32;
}
