package embwasm:threads;

/// @cpp-module: threads
/// @cpp-header: "embwasm_hostmodule_thread.hpp"
interface threads {
    /// @cpp-func: embwasm::hostmodules::thread::ThreadSpawn
    thread-spawn: func(name: string) -> s32;

    /// @cpp-func: embwasm::hostmodules::thread::ThreadYield
    thread-yield: func();

    /// @cpp-func: embwasm::hostmodules::thread::EventWait
    event-wait: func(event-id: s32);

    /// @cpp-func: embwasm::hostmodules::thread::EventSignal
    event-signal: func(event-id: s32);
}
